- name: Create GitHub Release
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: v1.0.0  # Use a dynamic version if needed
    release_name: "Version 1.0.0"
    draft: false
    prerelease: false

- name: Upload APK to Release
  uses: actions/upload-release-asset@v1
  with:
    upload_url: ${{ steps.create-release.outputs.upload_url }}
    asset_path: app/build/outputs/apk/debug/attendance_app_*.apk
    asset_name: attendance_app_1.0.apk
    asset_content_type: application/vnd.android.package-archive
